app/urls.py
from django.urls import path, include

from app.views.asistencia import views
from app.views.asistencia.views import *
from app.views.notas.views import *
from app.views.persona.views import *
from app.views.servicio.views import *

app_name = 'asys'

urlpatterns = [
    # path('get_inattendance_count/', views.get_inattendance_count, name='get_inattendance_count'),
    path('persona/list/', MembersListView.as_view(), name='miembro_list'),
    path('persona/add/', MembersCreate.as_view(), name='members_create'),
    path('persona/edit/<int:pk>/', MembersUpdate.as_view(), name='members_update'),
    path('persona/delete/<int:pk>/', MembersDelete.as_view(), name='members_delete'),

    # Url page Servico
    path('servicio/create/', login_required(ServicioCreateView.as_view()), name='servicio_create'),
    path('add-persona/', add_persona, name='add_persona'),
    path('servicio/list/', ServicioListView.as_view(), name='service_list'),
    path('service/edit/<int:pk>/', ServiceUpdate.as_view(), name='service_update'),
    path('service/delete/<int:pk>/', ServiceDelete.as_view(), name='service_delete'),

    # Url page Asistencia
    path('crear-asistencia/', AttendanceCreateView.as_view(), name='crear_asistencia'),
    path('lista-asistencia/', AttendanceList.as_view(), name='list_asistencia'),
    path('details/', AttendanceDetailsView.as_view(), name='details_asistencia'),
    path('guardar-status/', views.guardar_status, name='guardar_status'),
    path('asistencia/edit/<int:pk>/', AttendaceUpdate.as_view(), name='asistencia_update'),

    path('notas/list', NotaView.as_view(), name='nota_list'),
    path('notas/delete/<int:pk>/', NotaDeleteView.as_view(), name='nota_delete'),
    path('notas/cargar_mas/', cargar_mas_notas, name='cargar_mas_notas'),
    path('notas/update/<int:pk>/', NotaUpdateView.as_view(), name='nota_update'),


    # urls.py
    #     path('attendance/json/<str:date>/', AttendanceJsonDetail.as_view(), name='attendance_json'),
    #     path('lista-asistencia2/', AsistenciaDataTable.as_view(), name='list_asistencia2'),

]

setting/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from login.views import LoginFormView
from setting import settings

urlpatterns = [
    path('', LoginFormView.as_view(), name='login'),
    # path('register/', RegisterView.as_view(), name='register'),
    path('login/', include('login.urls')),
    path('admin/'
         '', admin.site.urls),
    path('asys/', include('app.urls')),
    path('select2/', include('django_select2.urls')),

    # path('', include('django.contrib.auth.urls'), name='login'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/views/notas/views.py
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.views.generic import CreateView, ListView, DeleteView, UpdateView
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from django.core import serializers

from app.forms import NotaForm
from app.models import Nota


class NotaView(CreateView, ListView):
    model = Nota
    form_class = NotaForm
    template_name = 'notas/listaNota.html'
    context_object_name = 'notas'
    success_url = reverse_lazy('asys:nota_list')
    ordering = ['-fecha_modificacion']  # Ordenar por fecha de modificación descendente

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        if request.headers.get('x-requested-with') == 'XMLHttpRequest' and request.method == "POST":
            import json
            body = json.loads(request.body)
            offset = int(body.get('offset', 0))
            limit = 3
            notas = Nota.objects.all().order_by('fecha_creacion')[offset:offset+limit]
            data = serializers.serialize('json', notas)
            return JsonResponse(data, safe=False)
        return super().post(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Listado de Notas'
        context['create_url'] = reverse_lazy('asys:nota_create')
        context['list_url'] = reverse_lazy('nota_list')
        context['entity'] = 'Nota'
        return context

@method_decorator(csrf_exempt, name='dispatch')
class NotaDeleteView(DeleteView):
    model = Nota
    success_url = reverse_lazy('asys:nota_list')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        return JsonResponse({'success': True})  


class NotaUpdateView(UpdateView):
    model = Nota
    form_class = NotaForm
    template_name = 'notas/listaNota.html'
    success_url = reverse_lazy('asys:nota_list')

    

@csrf_exempt
def cargar_mas_notas(request):
    if request.method == 'POST':
        offset = int(request.POST.get('offset', 0))
        limit = 3
        notas = Nota.objects.all().order_by('-fecha_modificacion')[offset:offset+limit]
        data = serializers.serialize('json', notas)
        return JsonResponse(data, safe=False)
    return JsonResponse({'error': 'Invalid request'}, status=400)

app/templates/notas/listaNota.html
{% extends 'body.html' %}
{% load custom_filters %}
{% load static %}

{% block contents %}
  <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet" />
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" />

  <link href="{% static 'css/styleCalendar.css' %}" rel="stylesheet" />
  <link href="{% static 'css/notas.css' %}" rel="stylesheet" />

  <!-- =========Este bloque es del calendario======== -->
  {% comment %} <div class="absolute" style="position: absolute; top: 150px; right: 0; width: 700px;">
    <div class="row">
      <div class="col-md-13">
        <div class="elegant-calencar d-md-flex">
          <div class="wrap-header d-flex align-items-center">
            <p id="reset">reset</p>
            <div id="headers" class="p-0">
              <div class="pre-button d-flex align-items-center justify-content-center">
                <i class="fa fa-chevron-left"></i>
              </div>
              <div class="head-info">
                <div class="head-day"></div>
                <div class="head-month"></div>
              </div>
              <div class="next-button d-flex align-items-center justify-content-center">
                <i class="fa fa-chevron-right"></i>
              </div>
            </div>
          </div>
          <div class="calendar-wrap">
            <table id="calendar">
              <thead>
                <tr>
                  <th>Sun</th>
                  <th>Mon</th>
                  <th>Tue</th>
                  <th>Wed</th>
                  <th>Thu</th>
                  <th>Fri</th>
                  <th>Sat</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                </tr>
                <tr>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                </tr>
                <tr>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                </tr>
                <tr>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                </tr>
                <tr>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                </tr>
                <tr>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div><br />
    <button type="button" class="btn btn-outline-info btn-sm" data-toggle="modal" data-target="#crearNota">Agregar Nota</button>
  </div> {% endcomment %}

  <!-- ======Este Bloque contiene el listado de la notas ============= -->
  {% if notas %}
  <div id="nota-container">
    <div class="card-deck">
      {% for nota in notas|slice:':3' %}
        <div class="card text-white bg-warning mb-3" data-id="{{ nota.id }}">
          <div class="card-header d-flex justify-content-between align-items-center">
            <strong>{{ nota.titulo|upper }}</strong>
            <cite class="blockquote-footer text-muted">{{ nota.fecha_creacion }}</cite>
          </div>
          <div class="card-body">
            <p>{{ nota.contenido }}</p>
          </div>
          <div class="card-footer d-flex justify-content-between">
            <a class="btn btn-primary update-link" href="{% url 'asys:nota_update' nota.id %}"><i class="fas fa-edit"></i> Editar</a>
            <a class="btn btn-danger delete-link" data-id="{{ nota.id }}" href="#" data-bs-toggle="modal" data-bs-target="#deleteModal">
                <i class="fas fa-trash-alt"></i> Eliminar
              </a>
              
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
  <div class="text-center">
    <button id="ver-mas" data-url="{% url 'asys:nota_list' %}" data-offset="3" class="btn btn-outline-info btn-sm">Ver más</button>
    <button type="button" class="btn btn-outline-info btn-sm" data-toggle="modal" data-target="#crearNota">Agregar Nota</button>
  </div>
{% else %}
  <div class="container" style="justify-items: center;  padding: 10; top: 80;">
    <p>No hay notas disponibles.</p>
    <button type="button" class="btn btn-outline-info btn-sm" data-toggle="modal" data-target="#crearNota">Agregar Nota</button>
  </div>
{% endif %}


  <!-- ======== ESte Bloque es para agregar la lista ======== -->
  <div class="modal fade" id="crearNota" tabindex="-1" role="dialog" aria-labelledby="crearNotaTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="crearNotaTitle">Agregar Nota</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        </div>
        <div class="modal-body">
          <form id="crearNotaForm" method="post" action="{% url 'asys:nota_list' %}">
            {% csrf_token %}

            <div class="form-group">
              <label for="titulo" class="col-form-label">{{ form.titulo.label|upper }}</label>
              {{ form.titulo }}
            </div>
            <div class="form-group">
              <label for="contenido" class="col-form-label">{{ form.contenido.label|upper }}</label>
              {{ form.contenido }}
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
              <button type="submit" class="btn btn-LightSeaGreen text-white"><i class="fas fa-save"></i> Guardar</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>

  <!-- Modal de eliminación -->
  <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <form method="post">
      {% csrf_token %}
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">Eliminar Nota</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <p>¿Estás seguro de que quieres eliminar esta nota?</p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
            <button type="button" id="confirm-delete" class="btn btn-danger">Eliminar</button>
          </div>
        </div>
      </div>
    </form>
  </div>
  


  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <script src="{% static 'js/notas.js' %}"></script>
  <script src="{% static 'js/popper.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>
{% endblock %}

app/templates/notas/notas.html
<!-- templates/notas/nota_form.html -->
{% extends 'body.html' %}
{% load custom_filters %}

{% block contents %}
  {% csrf_token %}
  <div class="contents">
    <h2>Crear Notas</h2>
    <div class="card text-white bg-warning mt-4 row">
      <form method="post">
        <div class="card-header row">{{ form.titulo.label|upper }}{{ form.titulo }}</div>
        <div class="card-body row">
          <h4>{{ form.contenido.label|upper }}</h4>
          {{ form.contenido }}
        </div>
      </form>
    </div>
    <button class="btn btn-LightSeaGreen text-white" type="submit"><i class="fas fa-save"></i> Guardar</button>
    <a href="{% url 'asys:nota_list' %}" class="btn btn-danger btn-flat"><i class="fas fa-times"></i> Cancelar</a>
  </div>

  <style>
    /* Estilos personalizados */
    .card-body input[type='text'],
    .card-body textarea {
      background-color: #f6b73c; /* Color de fondo deseado para input */
      color: white; /* Color de texto blanco */
      border: none; /* Elimina el borde si lo deseas */
      padding: 10px; /* Ajusta el relleno según sea necesario */
      width: 100%; /* Ajusta el ancho del input */
    }
    
    .card-header input[type='text'],
    .card-header textarea {
      background-color: #f6b73c; /* Color de fondo deseado para input */
      color: white; /* Color de texto blanco */
      border: none; /* Elimina el borde si lo deseas */
      padding: 10px; /* Ajusta el relleno según sea necesario */
      width: 100%; /* Ajusta el ancho del input */
    }
  </style>
{% endblock %}