app/urls.py
from django.urls import path, include

from app.views.asistencia import views
from app.views.asistencia.views import *
from app.views.notas.views import *
from app.views.persona.views import *
from app.views.servicio.views import *

app_name = 'asys'

urlpatterns = [
    # path('get_inattendance_count/', views.get_inattendance_count, name='get_inattendance_count'),
    path('persona/list/', MembersListView.as_view(), name='miembro_list'),
    path('persona/add/', MembersCreate.as_view(), name='members_create'),
    path('persona/edit/<int:pk>/', MembersUpdate.as_view(), name='members_update'),
    path('persona/delete/<int:pk>/', MembersDelete.as_view(), name='members_delete'),

    # Url page Servico
    path('servicio/create/', login_required(ServicioCreateView.as_view()), name='servicio_create'),
    path('add-persona/', add_persona, name='add_persona'),
    path('servicio/list/', ServicioListView.as_view(), name='service_list'),
    path('service/edit/<int:pk>/', ServiceUpdate.as_view(), name='service_update'),
    path('service/delete/<int:pk>/', ServiceDelete.as_view(), name='service_delete'),

    # Url page Asistencia
    path('crear-asistencia/', AttendanceCreateView.as_view(), name='crear_asistencia'),
    path('lista-asistencia/', AttendanceList.as_view(), name='list_asistencia'),
    path('details/', AttendanceDetailsView.as_view(), name='details_asistencia'),
    path('guardar-status/', views.guardar_status, name='guardar_status'),
    path('asistencia/edit/<int:pk>/', AttendaceUpdate.as_view(), name='asistencia_update'),

    path('notas/list', NotaView.as_view(), name='nota_list'),
    path('notas/delete/<int:pk>/', NotaDeleteView.as_view(), name='nota_delete'),
    path('notas/cargar_mas/', cargar_mas_notas, name='cargar_mas_notas'),
    path('notas/update/<int:pk>/', NotaUpdateView.as_view(), name='nota_update'),


    # urls.py
    #     path('attendance/json/<str:date>/', AttendanceJsonDetail.as_view(), name='attendance_json'),
    #     path('lista-asistencia2/', AsistenciaDataTable.as_view(), name='list_asistencia2'),

]

setting/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from login.views import LoginFormView
from setting import settings

urlpatterns = [
    path('', LoginFormView.as_view(), name='login'),
    # path('register/', RegisterView.as_view(), name='register'),
    path('login/', include('login.urls')),
    path('admin/'
         '', admin.site.urls),
    path('asys/', include('app.urls')),
    path('select2/', include('django_select2.urls')),

    # path('', include('django.contrib.auth.urls'), name='login'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>

<meta charset="UTF-8">
<title>Login</title>
<link rel="stylesheet" href="{% static 'css/login.css' %}"  id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>


<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!-- Include the above in your HEAD tag -->
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">


<!-- body form login -->
{% block login %}
{% endblock %}
</head>
</html>

templates/body.html
{% extends 'home.html' %}

{% block body %}
<!-- Incluye el Header -->
{% include 'header.html' %}



{% block contents %}
<!-- Contenido del cuerpo -->
{% endblock %}




{% block javascript  %}
<!--Java script static-->
{% endblock %}

<!-- Footer -->



{% endblock %}

templates/delete.html
{% extends 'body.html' %}
{% load widget_tweaks %}
{% block contents %}
<main class="container-fluid">
    <div class="row px-xl-6">
        <div class="col-14">
            <div class="d-flex align-items-center p-2 my-3 text-white bg-LightSeaGreen rounded shadow-sm">
                <div class="lh-2">
                    <i class="fa fa-list"></i> {{title}}
                </div>
            </div>
            <form method="post" action=".">


                <div class="my-3 p-3 bg-body rounded shadow-sm">
                    {% csrf_token %}
                    <input type="hidden" name="action" value="{{ action }}">
                    {% if form.errors %}
                    <div class="alert alert-danger alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h5><i class="icon fas fa-ban"></i> Ha ocurrido un error al querer guardar el registro</h5>
                        <ul>
                            {% for field in form %}
                            {% for error in field.errors %}
                            <li>{{ error }}</li>
                            {% endfor %}
                            {% endfor %}
                        </ul>
                    </div>
                    {% endif %}
                    <div class="alert alert-danger alert-dismissible">
                        <h5><i class="icon fas fa-ban"></i> Notificación!</h5>
                        ¿Estas seguro de eliminar el registro de {{ object.name }} {{ object.lastname }}?
                    </div>

                    <button type="submit" class="btn btn-LightSeaGreen text-white">
                        <i class="fas fa-save"></i> Si, aceptar
                    </button>
                    <a href="{{ list_url }}" class="btn btn-danger btn-flat">
                        <i class="fas fa-times"></i> Cancelar
                    </a>
                </div>


            </form>
        </div>
    </div>
</main>
<script>
    $('form').on('submit', function (e) {
        e.preventDefault();
        var parameters = new FormData(this);
        submit_with_ajax(window.location.pathname, 'Notificación', '¿Estas seguro de eliminar el siguiente registro?', parameters, function () {
            Swal.fire({
                title: 'Alerta',
                text: 'Registro eliminado correctamente',
                icon: 'success',
                timer: 2000,
                onClose: () => {
                    location.href = '{{ list_url }}';
                }
            }).then((result) => {

            });
        });
    });
</script>
{% endblock %}

templates/footer.html
{% load static  %}
<br>
<link href="{% static 'css/animate/animate.min.css' %}" rel="stylesheet">
<footer class="footer">
    <div class="container-fluid">
        <nav class="pull-left"></nav>
        <div class="copyright pull-right"> © 2024 Derechos Reservados</div>
    </div>
</footer>

templates/form.html
{% extends 'body.html' %} {% load widget_tweaks %} {% block contents %}

<main class="container-fluid">

	<div class="row px-xl-6">
		<div class="col-14">
			<form method="post" action="." enctype="multipart/form-data">
				{% csrf_token %}
				<div class="d-flex align-items-center p-2 my-3 text-white bg-LightSeaGreen rounded shadow-sm">
					<div class="lh-2">
						{% if action == 'add' %}
						<i class="fa fa-user-plus"></i> {% else %}
						<i class="fas fa-edit"></i> {% endif %} {{ title }}
					</div>
				</div>
				<div class="my-3 p-3 bg-body rounded shadow-sm">
					<input type="hidden" name="action" value="{{ action }}"> {% if form.errors %}
					<div class="alert alert-danger alert-dismissible">
						<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
						<h5><i class="icon fas fa-ban"></i> Ha ocurrido un error al querer guardar el registro</h5>
						<ul>
							{% for field in form %} {% for error in field.errors %}
							<li>{{ error }}</li>
							{% endfor %} {% endfor %}
						</ul>
					</div>
					{% endif %} {% block campos %} {% endblock %}
				</div>

				<button class="btn btn-LightSeaGreen text-white" type="submit"><i class="fas fa-save"></i> Guardar</button>
				<button href="{{create_url}}" class="btn btn-LightSeaGreen text-white" type="submit"><i class="fas fa-save"></i> Guardar y agregar otro</button>
				<a href="{{list_url}}" class="btn btn-danger btn-flat">
					<i class="fas fa-times"></i> Cancelar
				</a>
            </form>
		</div>
	</div>



</main><br>


<script>
    document.addEventListener('DOMContentLoaded', function () {

        const form = document.querySelector('form');
        form.addEventListener('submit', function (e) {
            e.preventDefault();

            const parameters = new FormData(this);
            const action = form.querySelector('input[name="action"]').value;

            fetch(window.location.pathname, {
                method: 'POST',
                body: parameters,
                headers: {
                    'X-Requested-With': 'XMLHttpRequest'
                }
            })
            .then(response => response.json())
            .then(data => {
                if (data.success) {
                    Swal.fire({
                        title: 'Success!',
                        text: action === 'add' ? 'El servicio ha sido creado exitosamente.' : 'El servicio ha sido actualizado exitosamente.',
                        icon: 'success'
                    }).then(() => {
                        window.location.href = '{{ list_url }}';
                    });
                } else {
                    let errorMessages = 'Se produjo un error al procesar su solicitud.';
                    if (data.errors) {
                        try {
                            const errors = JSON.parse(data.errors);
                            errorMessages = Object.keys(errors).map(field => {
                                return `${field}: ${errors[field].map(err => err.message).join(', ')}`;
                            }).join('\n');
                        } catch (e) {
                            errorMessages = data.errors;
                        }
                    }
                    Swal.fire({
                        title: 'Error!',
                        text: errorMessages,
                        icon: 'error'
                    });
                }
            })
            .catch(error => {
                Swal.fire({
                    title: 'Error!',
                    text: 'Se produjo un error al procesar su solicitud.',
                    icon: 'error'
                });
            });
        });

        // Input masks for DNI and phone
        Inputmask("999-9999999-9").mask(document.querySelector('[name="dni"]'));
        Inputmask("999-999-9999").mask(document.querySelector('[name="phone"]'));
        Inputmask("999-999-9999").mask(document.querySelector('[name="phone"]'));

        // Initialize datepickers
        $('.datepicker').datepicker({
            format: 'dd/mm/yyyy',
            autoclose: true,
            todayHighlight: true
        });
    });
</script>




<script>
    document.addEventListener('DOMContentLoaded', function() {
        new AutoNumeric('.money-input', {
            currencySymbol: '$',
            digitGroupSeparator: ',',
            decimalCharacter: '.',
            decimalPlaces: 2,
            minimumValue: '0',
            maximumValue: '9999999999.99'
        });
    });


</script>

{% block javascript %}
<!-- Aquí puedes añadir JavaScript adicional si es necesario -->
{% endblock %} {% endblock %}

templates/header.html
{% load static %}

  
    <!-- ======= Top Bar ======= -->
    <div id="topbar" class="d-flex align-items-center fixed-top">
      <div class="container d-flex align-items-center justify-content-center justify-content-md-between">
        <div class="align-items-center d-none d-md-flex">
          <i class="bi bi-person-check-fill"></i>Bienvenido, {{ user.first_name }} {{ user.last_name }}
        </div>
        <div class="d-flex align-items-center">
          <i class="bi bi-phone"></i> Call us now +1 5589 55488 55
        </div>
      </div>
    </div>
  
    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top">
      <div class="container d-flex align-items-center">
  
        <a href="{% url 'index' %}" class="logo me-auto"><img src="{% static 'assets/img/logo.png' %}" alt=""></a>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <h1 class="logo me-auto"><a href="index.html">Medicio</a></h1> -->
  
        <nav id="navbar" class="navbar order-last order-lg-0">
          <ul>
            <li><a class="nav-link scrollto " href="{% url 'index' %}">Home</a></li>
            <li><a class="nav-link scrollto" href="{% url 'asys:miembro_list' %}">Miembros</a></li>
            <li><a class="nav-link scrollto" href="{% url 'asys:service_list' %}">Servicios</a></li>
            <li class="dropdown"><a href="#"><span>Asistencia</span> <i class="bi bi-chevron-down"></i></a>
              <ul>
                <li><a href="{% url 'asys:list_asistencia' %}">Jovenes</a>
                
              </ul>
            </li>
            <li><a class="nav-link scrollto" href="{% url 'asys:nota_list' %}">Utilidades</a></li>
            <li class="dropdown"><a href="#"><span>Configuracion</span> <i class="bi bi-chevron-down"></i></a>
              <ul>
                <li><a href="#">Drop Down 1</a>
                
              </ul>
            </li>
            <li><a class="nav-link scrollto" href="#contact">Contacto</a></li>
          </ul>
          <i class="bi bi-list mobile-nav-toggle"></i>
        </nav><!-- .navbar -->
  
        <a href="{% url 'logout' %}" class="appointment-btn scrollto"><span class="d-none d-md-inline">Salir</span> </a>
  
      </div>

    </header><br><br><br><br><br><!-- End Header -->



<!-- 
<header class="container-fluid bg-dark mb-30">
    <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-primary" aria-label="Main navigation">
        <div class="container-fluid">
            <div class="col-lg-3">
                <a href="#" class="text-decoration-none">
                    <span class="h1 text-uppercase text-dark">AS</span>
                    <span class="h1 text-uppercase" style="color: white;">ys</span>
                </a>
            </div>

            <div class="navbar-collapse offcanvas-collapse" id="navbarsExampleDefault">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'asys:miembro_list' %}">Miembro</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-bs-toggle="dropdown"
                           aria-expanded="false">Asistencia</a>
                        <ul class="dropdown-menu" aria-labelledby="dropdown01">
                            <li><a class="dropdown-item" href="#">General</a></li>
                            <li><a class="dropdown-item" href="#">Dama</a></li>
                            <li><a class="dropdown-item" href="#">Caballeros</a></li>
                            <li><a class="dropdown-item" href="{% url 'asys:list_asistencia' %}">Jovenes</a></li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Servicio</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-bs-toggle="dropdown"
                           aria-expanded="false">Settings</a>
                        <ul class="dropdown-menu" aria-labelledby="dropdown01">
                            <li><a class="dropdown-item" href="#">Editar Perfil</a></li>
                            <li><a class="dropdown-item" href="#">Agregar Cargo</a></li>

                        </ul>
                    </li>
                </ul>
                <ul class="navbar-nav">
                    <li class="nav-item"><a href="{% url 'logout' %}" class="nav-link">Salir</a></li>
                </ul>

            </div>
        </div>
    </nav>
</header> -->

templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta name="csrf-token" content="{{ csrf_token }}">
    <title>Sistema de Registro</title>
    <meta content="" name="description" />
    <meta content="" name="keywords" />

    <!-- Favicons -->
    <link href="{% static 'assets/img/favicon.png' %}" rel="icon" />
    <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon" />

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet" />

    <!-- Vendor CSS Files -->
    <link href="{% static 'assets/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" />
    <link href="{% static 'assets/vendor/animate.css/animate.min.css' %}" rel="stylesheet" />
    <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet" />
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet" />
    <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet" />
    <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet" />
    <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet" />

    <!-- Bootstrap Datepicker CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" />

    <!-- Manejar los errores -->
    <link rel="stylesheet" href="{% static 'lib/jquery-confirm-v3.3.4/jquery-confirm.min.css' %}" />
    <link href="{% static 'css/helper.css' %}" rel="stylesheet" />
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.7.0.js"></script>

    <!-- Data table -->
    <link rel="stylesheet" href="{% static 'lib/datatables-1.10.20/css/dataTables.bootstrap4.min.css' %}" />
    <link rel="stylesheet" href="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/css/responsive.bootstrap4.min.css' %}" />

    <!-- Template MainMain CSS File -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet" />

    <!-- ======================Select2========================= -->
    <!-- <link href="{% static 'css/django_select2/select2.min.css' %}" rel="stylesheet"/> -->
    <!-- <script src="{% static 'css/django_select2/js/jquery.min.js' %}"></script> -->
    <!-- <script src="{% static 'css/django_select2/js/select2.full.min.js' %}"></script> -->
  </head>
  {% block head %}

  {% endblock %}

  <body class="bg-light">
    <!-- =================main====================== -->
    <body >
      {% block body %}

      {% endblock %}
    </body>

    <div id="preloader"></div>
    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.inputmask/5.0.6/jquery.inputmask.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/offcanvas.js' %}"></script>

    <!-- Bootstrap Datepicker JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
    <!-- Manejo de errores -->
    <script src="{% static 'lib/jquery-confirm-v3.3.4/jquery-confirm.min.js' %}"></script>
    <script src="{% static 'lib/sweetalert2-9.10.0/sweetalert2.all.min.js' %}"></script>
    <script src="{% static 'js/functions.js' %}"></script>

    <!-- Data Table -->
    <script src="{% static 'lib/datatables-1.10.20/js/jquery.dataTables.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/js/responsive.bootstrap4.min.js' %}"></script>

    <!-- Vendor JS Files -->
    <script src="{% static 'assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
    <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
    <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

    <!-- Template Main JS File -->
    <script src="{% static 'assets/js/main.js' %}"></script>

    {% block javascript %}
      <script type="text/javascript"></script>
    {% endblock %}
  </body>
</html>

templates/list.html
{% extends 'body.html' %} {% load static %} {% load custom_tags %} {% block head %} {% block head_list %} {% endblock %} {% endblock %} {% block contents %}
<main class="container-fluid">

	<!--Modar notificacion-->
	{% if messages %} {% for message in messages %} {% if 'modal_trigger' in message.extra_tags %}
	<!-- Este bloque de codigo se utiliza para mostrar el modal de notificacion por inasistencia  -->
	<div class="modal" id="modal-{{ message.extra_tags.miembro_id }}" tabindex="-1" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<h1 class="modal-title fs-5" id="staticBackdropLabel">Notificación</h1>
				</div>
				<form method="post" action="{% url 'asys:guardar_status' %}" onsubmit="return enviarFormulario(event, '{{ message.extra_tags.miembro_id }}');">

					{% csrf_token %}
					<input type="hidden" name="id" id="id-{{ message.extra_tags.miembro_id }}" value="{{ message.extra_tags|extract_id }}">
					<div class="modal-body">
						<p>{{ message.message }}</p>
						<div class="form-check">
							<input class="form-check-input" type="radio" name="status" id="flexRadioDefault1" value="enfermo" checked>
							<label class="form-check-label" for="flexRadioDefault1">Miembro se encuentra enfermo
                           </label>
						</div>
						<div class="form-check">
							<input class="form-check-input" type="radio" name="status" id="flexRadioDefault2" value="visitar">
							<label class="form-check-label" for="flexRadioDefault2">Miembro necesita ser visitado
                           </label>
						</div>
						<div class="form-check">
							<input class="form-check-input" type="radio" name="status" id="flexRadioDefault3" value="permiso">
							<label class="form-check-label" for="flexRadioDefault3">Miembro tiene permiso o excusa
                           </label>
						</div>
					</div>
					<div class="modal-footer">
						<button type="submit" class="btn btn-secondary">Entendido</button>
					</div>
				</form>
			</div>
		</div>
	</div>
	{% endif %} {% endfor %} {% endif %}
	<script src="{% static 'asistencia/js/asistencia.js' %}"></script>
	<!--    --------Aqui termina el bloque de inasistencia ---------------------------->


	<!--Este Modal muestra el detallaes de asistencia Cuando se hace clic en el hojo o boton de la lista-->
	<div class="modal fade" id="detailsModal" tabindex="-1" role="dialog" aria-labelledby="detailsModalLabel" aria-hidden="true">
		<div class="modal-dialog modal-lg" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title" id="detailsModalLabel">Detalles de Asistencia</h5>
				</div>
				<div class="modal-body">
					<table class="table display table-bordered table-striped table-hover table-sm id stripe row-border order-column nowrap" id="detailsTable">
						<thead>
							<tr class="table-primary">
								<th scope="col">ID</th>
								<th scope="col">Nombre</th>
								<th scope="col">Fecha de Registro</th>
								<th scope="col">Presente</th>
							</tr>
						</thead>
						<tbody></tbody>
					</table>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
				</div>
			</div>
		</div>
	</div>

	<!--    Este bloque muestra un detalle en la pantalla de lista de miembro al hacer clic-->
	<div style="width: 100%; display: flex; justify-content: center;">
		<div id="detalle" class="card" style="display: none; ">
			<button type="button" class="close-button">&#x2716;</button>
			<div class="card-body">
				<div class="card-img-container">
					<img src="" id="perfil" alt="Foto de perfil">
				</div>
				<div class="card-details">
					<h2 id="nombre-empleado"></h2>
					<p id="dni-empleado"></p>
					<p id="nacimiento-empleado"></p>
					<p id="genero-mpleado"></p>
					<p id="telefono-empleado"></p>
					<p id="direccion-empleado"></p>
					<p id="ingreso-empleado"></p>
					<p id="correo-empleado"></p>
					<p id="estado-empleado"></p>
					<p id="cargo-empleado"></p>
				</div>
			</div>
		</div>

	</div>

	<div class="row px-xl-6">
        <div class="col-14">
                <div class="d-flex align-items-center p-2 my-3 text-white bg-LightSeaGreen rounded shadow-sm">
                    <div class="lh-2">
                        <i class="fa fa-list"></i> {{title}}
                    </div>
                </div>

                <div class="my-3 p-3 bg-body rounded shadow-sm">
                    <table class="table display table-bordered table-striped table-hover table-sm id stripe row-border order-column nowrap" id="data">
                        <thead>
                            {% block columns %} {% endblock %}
                        </thead>
                        <tbody>
                            {% block rows %} {% endblock %}
                        </tbody>
                    </table>

                    <div class="card-footer">
                        <a href="{{create_url}}" class="btn btn-LightSeaGreen btn-flat btnTest text-white">
                            <i class="fas fa-plus"></i> Nuevo registro
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %} {% block javascript %} {% endblock %}